# Generated by Django 5.1.6 on 2025-05-21 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_foodentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodentry',
            options={'ordering': ['-entry_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Lunch', max_length=20),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='name',
            field=models.CharField(default='Untitled Food', max_length=255),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='number_of_servings',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='serving_size_unit',
            field=models.CharField(default='g', max_length=20),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
