# Generated by Django 5.1.6 on 2025-05-21 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_foodentry_options_remove_foodentry_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calories_per_100g', models.FloatField()),
                ('carbs_per_100g', models.FloatField(default=0)),
                ('fat_per_100g', models.FloatField(default=0)),
                ('protein_per_100g', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='protein',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='food_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='users.fooditem'),
        ),
    ]
