# Generated by Django 5.0.2 on 2025-05-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_convert_existing_food_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='name',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fdc_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='food_name',
            field=models.CharField(default='Unknown Food', max_length=255),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='serving_size',
            field=models.FloatField(default=100.0),
        ),
    ]
