# Generated by Django 5.1.6 on 2025-03-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
